### PR TITLE
Store/restore "main" geometry/state - window and the file tree header

### PR DESCRIPTION
**Pull request by yarikoptic**
It felt inconvenient to need to rescale header (columns) in the tree view each time and/or make window bigger.  I guess there could be more geometries and states to store/restore but this is the main ones I felt need for.

I guess such functionality could become configurable, but as IMHO should be enabled by default for better UX decided to suggest hardcoded first.

### CODE REVIEW

**Comment by mih** [comment]
Great convenience upgrade! Thx!

It seems that the store is coming too late on deinit. not sure how exactly that happens. It may be a side-effect of the test setup.

**Comment by yarikoptic** [comment]
I will look into it later. Works for you ok locally?

**Comment by mih** [comment]
> I will look into it later. Works for you ok locally?

Yes, perfect. Keep window geometry and FSBrowser column widths.

**Comment by yarikoptic** [comment]
I have pushed f1d1b5151b1038db4201cdd7ddec6b4f6dcb55c3 but not sure if that is the best way or you (or I) would like it - dilutes somewhat `main_window` logic etc. Please see commit for more description.  I did try to just "monkey patch" .closeEvent upon that `load_ui` but for some reason it didn't quite work for some reason.

**Review by mih — APPROVED** [review]
Ok, so here is my summary of what this does:

- New `GooeyQMainWindow()` to handle `closeEvent`
- For that to work, the UI spec file and the loader had to be adjusted to support this custom class
- `main_window` is kept as a getter, but has no function anymore (note to self, remove comment about cached property)

> I feel, that more should be concentrated in such a class/closeEvent so there would be no need for manual calling of deinit

I agreee.

> To me it is not clear (due to my ignorance in Qt programming) why we need the GooeyApp(QObject), i.e. why it is not QMainWindow subclass right away, and thus dissolving all .main_window or why it is not just (object) and thus just providing some common logic but nothing really Qt

Other parts of the code are moving away from multiplexing widgets with other controlling functionality. The classes become needlessly complex and harder to grasp. Moreover, it is an explicit goal of the implementation to perform the least possible amount of tweaking standard Qt functionality. In cases like this, a subclass is the right way to go. But often the right call through the normal API is all it needs, leading to less code that needs maintenance.

The `GooeyApp` class uses signal/slots for communication. Only `QObjects` can do that. Just being a plain `object` is not possible.

**Comment by mih** [comment]
After having used this for a while now, I am thinking of reverting this PR.

Two reasons:

- Geometry *changes* of the main window do not save reliably. I am left with some "not-the-last" configuration for the outer window, although the header geometry in the browser widget seems to save properly every time
- The UI file become uneditable in the designer. The main window layout is unrecognized (showing menubar and statusbar on top of each other), and any attempt to save an adjusted UI file leads to a runtime error on startup:

```
Designer: Attempt to add a layout to a widget 'MainWindow' (GooeyQMainWindow) which already has a layout of non-box type QMainWindowLayout.
This indicates an inconsistency in the ui-file.
[ERROR  ] Could not locate widget cmdTab (QWidget) (RuntimeError) 
```

**Pull request merged**
