### PR TITLE
Add tests for `lsdir`

### PR DESCRIPTION
**Pull request by jsheunis**
This PR adds a few tests for `lsdir.py`. I would appreciate a good review, since this is the first time I've used mock patching.

In partial fulfilment of #48

### CODE REVIEW

**Comment by jsheunis** [comment]
Ok looks like the `crippled-filesystems` tests fail.

Specifically two tests:

#### 1: `test_lsdir.py::test_lsfiles`

The crippled filesystem is not picking up the symlinks, so the output from  `gooey-lsdir` is 7 items instead of the original 10 (with 3 symlinks), which leads to an assertion error. Is there a way to detect whether the code is running on a crippled filesystem and then to make the assert conditional?

#### 2: `test_lsdir.py::test_inaccessible_directory`

This is the code that fails:

```
def test_inaccessible_directory(temp_dir_name: str = ""):
        new_dir = Path(temp_dir_name) / 'inaccessible_dir'
        new_dir.mkdir(0o444)
        with assert_raises(IncompleteResultsError):
            res = list(GooeyLsDir.__call__(Path(temp_dir_name)))
            assert_equal(len(res), 1)
>           assert_equal(res[0].get('status'), 'error')

---

first = 'ok', second = 'error', msg = None
```

Does this have to do with how the permissions are set in the testing directory with the `new_dir.mkdir(0o444)` command? FYI this works locally on my Mac, i.e. an `IncompleteResultsError` is raised and it returns the result record with error status and permission denied message. My intention was to create a directory with no access permissions. Is there a better way to achieve this?

**Comment by mih** [comment]
A dataset repo has a method `is_managed_branch()` that can be used as an indicator for a crippled FS.

Setting reduced permissions is also something that can be limited by FS capabilities. You could apply the same test, or possibly very the set permissions.

**Review by mih — COMMENTED** [review]
Thx, the tests look good to me in general (made comments above)

**Comment by jsheunis** [comment]
Ok, now test succeed with crippled fs workflow, but still fail on windows with appveyor. Looks like it detects a crippled filesystem, but still recognizes symlinks. I had thought that these two were mutually inclusive. Should I be testing for both?

**Comment by mih** [comment]
Windows can do symlinks but is otherwise crippled. These are more or less orthogonal. Welcome to cross-platform hell 🍻

**Comment by jsheunis** [comment]
Thank! :)

**Review by mih — APPROVED** [review]
LGTM! Thx!

**Pull request merged**
