### PR TITLE
Move windows installer generation code into this repository

### LINKED ISSUE #258: Migrate installer release workflow here
Currently at https://github.com/christian-monch/datalad-gooey-windows-installer

### PR DESCRIPTION
**Pull request by christian-monch**
Fixes #258 

This PR moves the windows installer build-action into this repository. The windows installer build-action has to be triggered manually, where a revision ---by default `main`--- can be chosen from which the release should be built. <strike>The installer is deposited under a new release with a tag in the form of `windows-<YYYYMMDDHHMM>-<version>`, e.g.

``` 
windows-202210061139-0.1.0+76.g3cf7dda
```
</strike>

The installer is deposited under the latest release. The name of the installer will be `datalad-gooey-<version>-installer-amd64.exe`, e.g. [datalad-gooey-0.1.0+120.g34e85f6-installer-amd64.exe](https://github.com/datalad/datalad-gooey/releases/download/0.1.0/datalad-gooey-0.1.0+120.g34e85f6-installer-amd64.exe).

<strike>and a name in the form `windows <YYYYMMDDHHMM>-<version>` (the timestamp and version are identical in the tag and the release name). For an example see [this release in christian-monch/datalad-gooey](https://github.com/christian-monch/datalad-gooey/releases/tag/windows-202210061139-0.1.0+76.g3cf7dda)</strike>

*NB! the PR is difficult to test before merging because GitHub looks only in `main` for actions. It is working on my fork of this repository, where I merged the branch `issue-258-move-installer` into `main`.*

### CODE REVIEW

**Review by mih — APPROVED** [review]
Let's do it! What could go wrong? ;-)

Thx!

**Comment by christian-monch** [comment]
> Let's do it! What could go wrong? ;-)

Nothing ;-)

I should mention though, that we have to add an access token to the repository secrets that is authorized to create releases.


image

**Comment by mih** [comment]
Please let me know which scopes are needed for that, and I create one. Or which permissions you need to be able to do that yourself. Thx

**Comment by christian-monch** [comment]
@mih added a token.

But I don't see the action in the Actions-tab. Do you?

**Comment by mih** [comment]
I don't see it, but I am also not sure what to look for. I also don't know what the screenshot refers to that you posted. Can you link to that place or describe what it is that needs doing?

**Comment by christian-monch** [comment]
I fixed it by creating a branch in this repository that contains a very slight modification of the windows installer build-workflow. Since the workflow then comes from a "local" branch, it is automatically approved.

(I was referring to [this chapter in github docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks).)

**Pull request merged**
