### PR TITLE
Add cmdui test

### PR DESCRIPTION
**Pull request by bpoldrack**
This demos how to test UI parts with pytest-qt, including "clicking buttons" instead of calling functions directly from within the tests.

The test doesn't have a lot of assertions yet, but (hopefully) shows how to "click buttons with pytest-qt".

Ping #48

### CODE REVIEW

**Comment by mih** [comment]
Tried to resolve the Mac-issue, but failed. Made some improvements nevertheless and pushed them here.

**Comment by adswa** [comment]
Running tests on this branch I get a local failure:
```
==================================================== FAILURES ====================================================
_____________________________________________ test_GooeyDataladCmdUI _____________________________________________

gooey_app = <datalad_gooey.app.GooeyApp(0x7efff0016170) at 0x7effe69f8ac0>

    def test_GooeyDataladCmdUI(gooey_app, *, qtbot):
        qtbot.addWidget(gooey_app.main_window)
        cmdui = GooeyDataladCmdUI(gooey_app, gooey_app.get_widget('cmdTab'))
    
        cmdui.configure('wtf', {})
    
        # command tab is set up:
        assert_true(cmdui.pwidget.isEnabled())
        assert_equal(
            gooey_app.get_widget('contextTabs').currentWidget().objectName(),
            "cmdTab")
        assert_equal(cmdui._cmd_title.text().lower(), "wtf")
    
        # click OK and see the correct signal:
        buttonbox = cmdui.pwidget.findChild(QDialogButtonBox, 'cmdTabButtonBox')
        ok_button = [b for b in buttonbox.findChildren(QPushButton)
                     if b.text() == "OK"]
>       assert_equal(len(ok_button), 1)

```

(ok_button is an empty list)
Have you seen this before by any chance? First time running gooey tests,  I might do something wrong that someone else figured out already, so asking for advice early...

**Comment by bpoldrack** [comment]
@adswa 
> Edit: The QPushButtons have an additional `&` in their text, which is why `ok_button` is length 0:
> 
> ```
> (Pdb) p buttonbox.findChildren(QPushButton)[0].text()
> '&OK'
> (Pdb) p buttonbox.findChildren(QPushButton)[1].text()
> '&Cancel'
> ```

I have not seen this. What system are you running the tests on?

**Comment by adswa** [comment]
> I have not seen this. What system are you running the tests on?

Debian bookworm/sid

**Comment by bpoldrack** [comment]
@adswa: https://github.com/datalad/datalad-gooey/pull/165/commits/7d1f7459f9716ac34d71fc21a1abdb4e75ec2246 should fix it for you.

@mih: Mac issue seems to not reproduce anymore.

**Review by mih — APPROVED** [review]
OK, cool! Let's try things in production. Thx!

**Pull request merged**
