### PR TITLE
Add a gooey-only installer that can be installed without admin privileges

### PR DESCRIPTION
**Pull request by christian-monch**
This PR implements option 1 of issue #425. It modifies the "Build Windows Installer action to build a second installer that will only install `datalad-gooey`, `datalad`, and `python 3.9` in user directories, i.e. `<user>\AppData\Local\datalad.org`.

### CODE REVIEW

**Review by adswa — APPROVED** [review]
Thanks @christian-monch. I left two small wording suggestions for the docs. 
I tested both installers on Windows 10, and they seemed to work as advertised - yay!
I only have two general remarks, probably for a follow-up PR:
The overview of releases currently looks like this

image

I suspect that the Git-SHA-based name looks more weird to many users than the old installer with the "clean" v0.2.0. Should we do a patch release in order to have those two most recent installers readily and easily identifiable? 

I noticed when using the full installer that Git 2.37.3 was being installed, this is 5 minor versions below the current version and was released more than one year ago. Its likely useful to update this. If users already have a more recent git version they would otherwise be forced to downgrade.

**Review by adswa — CHANGES_REQUESTED** [review]
ah wait, one second - something is weird. I did not notice the first time I ran the full installer, but when I redid it after wiping everything just for good measure, I noticed that the full installer does not seem to install git-annex anymore? I can't pinpoint where in this PR this would happen, but executing the full installer on an admin account does not prompt for the admin password, and does not install git-annex.

**Comment by christian-monch** [comment]
> ah wait, one second - something is weird. I did not notice the first time I ran the full installer, but when I redid it after wiping everything just for good measure, I noticed that the full installer does not seem to install git-annex anymore? I can't pinpoint where in this PR this would happen, but executing the full installer on an admin account does not prompt for the admin password, and does not install git-annex.

Thanks for the report. Checking this now

**Comment by christian-monch** [comment]
Thanks a lot @adswa 

> Thanks @christian-monch. I left two small wording suggestions for the docs. I tested both installers on Windows 10, and they seemed to work as advertised - yay! I only have two general remarks, probably for a follow-up PR: The overview of releases currently looks like this
> 
> image
> 
> I suspect that the Git-SHA-based name looks more weird to many users than the old installer with the "clean" v0.2.0. Should we do a patch release in order to have those two most recent installers readily and easily identifiable?
> 
Yes, will do that

> I noticed when using the full installer that Git 2.37.3 was being installed, this is 5 minor versions below the current version and was released more than one year ago. Its likely useful to update this.

Good point. Created https://github.com/datalad/datalad-gooey/issues/434 and assigned it to myself.


> If users already have a more recent git version they would otherwise be forced to downgrade.
Thanks for noticing that. Users might indeed downgrade, but they are not forced to do that. Users are free to cancel the git installation. I added a note about this topic to the installation instructions for windows

**Comment by christian-monch** [comment]
> ah wait, one second - something is weird. I did not notice the first time I ran the full installer, but when I redid it after wiping everything just for good measure, I noticed that the full installer does not seem to install git-annex anymore? I can't pinpoint where in this PR this would happen, but executing the full installer on an admin account does not prompt for the admin password, and does not install git-annex.

Found it. The git-annex installer, which requests admin privileges, is only started by an installer that has requested admin privileges. Long story short, I fixed by requesting admin level for the full installer.

**Review by adswa — APPROVED** [review]
I tried the full installer and can confirm that git-annex gets installed - thanks!

**Pull request merged**
